# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af07e6091b84ac45050ac680a925a7016f1c484db58c415c118863d3a250454653c302c9b11d9c986e179f5fc91fcfb8973b9128997770518c4d265c4e36a0a6

test:
  secret_key_base: 2baf31a3053ed1e322b213fa125910c78ddb7393bd23be1cd6f0845fb5c1a2b07bad8462297426eb8a823537e321c5bab4d19ba1f5d39d14f508118d145cc357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
